# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05e0655f850ddd2609b224972d01ed1e330748b8beed303a1f8021c51ca411c150ebfc557877839838a70c0ad1d9ea7a1d539215ffe9497c41651988b5618383

test:
  secret_key_base: 45bffef45c3d310e52ee89710ad9f53d7c10955481cddedac42723b026ce4587b5daada4ce5d4867a27cecd7b6a86d6ebc9a04635a5d5e369b3010a015344448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
